[package]
name = "dbm-mongodb-plugin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mongodb-plugin"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
async-trait = "0.1"
dbm-plugin-rpc = { path = "../common-rpc" }
mongodb = { version = "2.8", default-features = false, features = ["tokio-runtime"] }
bson = "2.9"
futures = "0.3"
